### ISSUE TITLE
Add "Dashboard" button to sidebar

### ISSUE THREAD

**Issue by bmeeder22** [booradleyfoundation/cowchips-admin#89]
**Is your feature request related to a problem? Please describe.**
As a user I would like to be able to navigate back to the dashboard via the sidebar

**Describe the solution you'd like**
Add the link to the dashboard to the homescreen, the sidebar config JSON can be found here: https://github.com/booradleyfoundation/cowchips-admin/blob/master/src/_nav.js

**Comment by jschuckm** [comment]
https://github.com/booradleyfoundation/cowchips-admin/commit/6706a80d8ea0ebe2cb19a466c7c64a8cc74cdfd0
